# Generated by Django 5.2.5 on 2026-04-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingslot',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='digest_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
