# Generated by Django 5.2.5 on 2025-09-19 11:03

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('users', '0002_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role_title', models.CharField(default='System Administrator', max_length=100)),
                ('responsibilities', models.TextField(blank=True, help_text='Notes on admin responsibilities.')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('office_location', models.CharField(blank=True, max_length=100)),
                ('courses_taught', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of course codes you teach.', through='users.CourseTag', to='taggit.Tag', verbose_name='Courses Taught')),
            ],
        ),
        migrations.AddField(
            model_name='coursetag',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lecturerprofile'),
        ),
        migrations.CreateModel(
            name='ResearchAreaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lecturerprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='research_areas',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of research areas.', through='users.ResearchAreaTag', to='taggit.Tag', verbose_name='Research Areas'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('year_of_study', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, help_text='A short bio about yourself.')),
                ('skills', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of skills.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Skills')),
            ],
        ),
    ]
