# Generated by Django 5.2.5 on 2025-09-19 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('LEADER', 'Group Leader'), ('CO_LEADER', 'Co-Leader'), ('MEMBER', 'Member')], default='MEMBER', max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_code', models.CharField(help_text='e.g., SOFTENG 350', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('creator', models.ForeignKey(limit_choices_to={'role': 'LECTURER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='e.g., 1 for the first milestone, 2 for the second...')),
                ('project_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_templates', to='projects.projecttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projecttemplate'),
        ),
    ]
