# Generated by Django 5.2.5 on 2025-09-21 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_teammembership_role_projecttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['due_date']},
        ),
        migrations.AddField(
            model_name='milestone',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='milestones', to=settings.AUTH_USER_MODEL),
        ),
    ]
