# Generated by Django 5.2.5 on 2026-04-12 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_options_alter_invitation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INVITATION', 'Invitation'), ('INVITATION_ACCEPTED', 'Invitation Accepted'), ('INVITATION_DECLINED', 'Invitation Declined'), ('INVITATION_EXPIRED', 'Invitation Expired'), ('INVITATION_CANCELLED', 'Invitation Cancelled'), ('FILE_UPLOADED', 'File Uploaded'), ('FILE_VERSION_CREATED', 'File Version Created'), ('FILE_DELETED', 'File Deleted'), ('FILE_RESTORED', 'File Restored'), ('FILE_QUOTA_WARNING', 'File Quota Warning'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_REASSIGNED', 'Task Reassigned'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_BLOCKED', 'Task Blocked'), ('TASK_DEADLINE_REMINDER', 'Task Deadline Reminder'), ('TASK_OVERDUE', 'Task Overdue'), ('TASK_COMMENTED', 'Task Commented'), ('MILESTONE', 'Milestone'), ('PROJECT', 'Project')], max_length=30),
        ),
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_file_folders', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_folders', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('stored_file_name', models.CharField(max_length=255)),
                ('file_extension', models.CharField(blank=True, max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('current_version_number', models.PositiveIntegerField(default=1)),
                ('tag', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final'), ('REFERENCE', 'Reference'), ('ARCHIVE', 'Archive')], default='DRAFT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deletion_timestamp', models.DateTimeField(blank=True, null=True)),
                ('current_version_note', models.TextField(blank=True)),
                ('version_lock_expires_at', models.DateTimeField(blank=True, null=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_files', to='projects.filefolder')),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_project_files', to='projects.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_files', to=settings.AUTH_USER_MODEL)),
                ('version_lock_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_locked_project_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFileActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VERSION_CREATED', 'Version Created'), ('RENAMED', 'Renamed'), ('MOVED', 'Moved'), ('DELETED', 'Deleted'), ('RESTORED', 'Restored'), ('DOWNLOADED', 'Downloaded'), ('TAG_UPDATED', 'Tag Updated')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='projects.projectfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_activity_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('stored_file', models.FileField(upload_to='project_files/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('version_note', models.TextField(blank=True)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('tag_at_time', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final'), ('REFERENCE', 'Reference'), ('ARCHIVE', 'Archive')], default='DRAFT', max_length=20)),
                ('parent_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.projectfile')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_file_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number', '-upload_timestamp'],
                'unique_together': {('parent_file', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='projectfile',
            name='current_version_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.projectfileversion'),
        ),
        migrations.CreateModel(
            name='ProjectTrash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_timestamp', models.DateTimeField(auto_now_add=True)),
                ('scheduled_purge_date', models.DateTimeField()),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_project_files', to=settings.AUTH_USER_MODEL)),
                ('original_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trash_entry', to='projects.projectfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trash_entries', to='projects.project')),
            ],
            options={
                'ordering': ['-deletion_timestamp'],
            },
        ),
    ]
