# Generated by Django 5.2.5 on 2026-04-15 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_notification_type_filefolder_projectfile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('TASK_DEADLINE', 'Task Deadline'), ('PROJECT_DEADLINE', 'Project Deadline'), ('MEETING', 'Meeting'), ('MILESTONE', 'Milestone'), ('CUSTOM', 'Custom')], max_length=30)),
                ('related_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_visible_to_all_members', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='projects.project')),
            ],
            options={
                'ordering': ['start_datetime', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('MY_PROJECTS', 'My Projects'), ('MY_TASKS', 'My Tasks'), ('RECENT_ACTIVITY', 'Recent Activity'), ('CALENDAR', 'Calendar'), ('NOTIFICATIONS', 'Notifications'), ('PROJECT_HEALTH', 'Project Health'), ('TEAM_CONTRIBUTION', 'Team Contribution'), ('WORKLOAD', 'Workload Distribution')], max_length=40)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('user', 'widget_type')},
            },
        ),
        migrations.CreateModel(
            name='LecturerAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_PROGRESS', 'Low Progress'), ('MANY_OVERDUE', 'Many Overdue Tasks'), ('INACTIVE', 'No Recent Activity'), ('BLOCKED_STALE', 'Blocked Task Stale'), ('NO_FINAL_FILE', 'No Final File Near Deadline')], max_length=40)),
                ('alert_message', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_alerts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_alerts', to='projects.project')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'unique_together': {('lecturer', 'project', 'alert_type', 'is_resolved')},
            },
        ),
        migrations.CreateModel(
            name='ProjectSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.project')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('project', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('FINAL_FILE', 'Final File Exists'), ('TASKS_COMPLETE', 'Tasks Completed Or Closed'), ('TEAM_ACTIVE', 'All Members Recently Active'), ('DESCRIPTION_FILLED', 'Project Description Filled'), ('LECTURER_ASSIGNED', 'Lecturer Assigned')], max_length=40)),
                ('is_passed', models.BooleanField(default=False)),
                ('override_acknowledged', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_checklist_overrides', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_checklist_items', to='projects.project')),
            ],
            options={
                'ordering': ['item_type'],
                'unique_together': {('project', 'item_type')},
            },
        ),
    ]
